version: '3'

services:
  backend:
    build: ./backend
    restart: always
    networks:
      - tp1
    ports:
      - 3000:3000
  frontend:
    build: ./frontend
    restart: always
    networks:
      - tp1
    ports:
      - 5173:80


networks:
  tp1:
    driver: bridge
